### ISSUE TITLE
Undefined method "simple_form_for"

### ISSUE THREAD

**Issue by fidel-techprep** [appdev-projects/photogram-industrial#1]
I'm getting an ActionView::TemplateError when running rake grade. It seems like I need to add "simple_form" gem. It should be included with Devise? It's in the Gemfile.lock. When I add "simple_form" to the Gemfile the test passes.

<img width="887" alt="image" src="https://github.com/appdev-projects/photogram-industrial/assets/127764786/845e6cd6-a3c2-4be6-8214-f07129cc5a17">

cc: @heratyian

**Comment by bpurinton** [comment]
@fidel-techprep keep these issues coming! You're saving a lot of trouble for the next students to reach these projects, thanks a ton. I added the `simple_form` gem to the project ([on this recent commit](https://github.com/appdev-projects/photogram-industrial/commit/f892a5ab92d1288ee4ac4efe39b9df2763e5abc9)), so future forkers shouldn't have this issue.

**Comment by fidel-techprep** [comment]
Thank you, Ben! I'm happy to help and I am learning so much as I go through the lessons!
