### ISSUE TITLE
Sample Data 

### ISSUE THREAD

**Issue by JaredBears** [appdev-projects/photogram-industrial#3]
This is in relation to Photogram Industrial Part 2, when it is time to generate sample data.

With the Follow Requests, I noticed when running the provided code that it had users following themselves, which seems like unintentional behavior and causes the task to take longer than it should.  

I solved this by adding `next if first_user == second_user` to the sample data generation task:
```ruby
  users.each do |first_user|
    users.each do |second_user|
      next if first_user == second_user
```

I also added the following custom validation to the follow_requests table:
```ruby
  validate :sender_cant_follow_self

  def sender_cant_follow_self
    if sender_id == recipient_id
      errors.add(:sender_id, "can't follow self")
    end
  end
```

**Comment by bpurinton** [comment]
Well done! I'm going to leave off the custom validation (though I do like it) but I'll add the `sample_data` update to the lesson notes.

See these commits:

- Project: https://github.com/appdev-projects/photogram-industrial/commit/336c50cc600bc72bf5896f20f911f8e1ffee150b
- Lesson: https://github.com/appdev-lessons/photogram-industrial-part-2/commit/3f7b57baa10d2ac421427fb5554224711c49f983
